services:
  db:
    image: postgres:15
    container_name: movie_lottery_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
      
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie_lottery_app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - KINOPOISK_API_KEY=${KINOPOISK_API_KEY}
      - KINOPOISK_TOKEN=${KINOPOISK_API_KEY}
      - KP_TOKEN=${KINOPOISK_API_KEY}  
    ports:
      - "8888:8000"  # Откроет сайт на http://<IP_твоего_ПК>:8080
    networks:
      - appnet

  # Удобная веб-админка базы (опционально)
  adminer:
    image: adminer:4
    container_name: movie_lottery_adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:8080"  # Adminer: http://<IP_твоего_ПК>:8081
    environment:
      TZ: ${TZ}
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge
